### ISSUE TITLE
Adjust tax calculations in Daily Bread

### ISSUE THREAD

**Issue by anderspeders** [openspending/wheredoesmymoneygo.org#11]
Currently the non-taxable "personal allowance" seems actually to be taxed. 

See user today below, and let me know if I can help elaborate.  

User response:
However in 'The Daily Bread' section, the sliding scale starts at £10,000 with minimum amount going to tax being £4651 of the £10,000. I was just wondering if you have left an allowance for the non-taxable 'personal allowance'. The allowance of the tax year 2013/14 is £9,440. So if a person earned £10,000 the actual tax they would pay is £112 (basic 20%) + £270 of national insurance. 
Correct me if I'm wrong but doesn't that equal £382 instead of the quoted £4651 on your website?

**Comment by nigelbabu** [comment]
The dailybread calculates taxes for 2010 as explained here: http://openspending.org/blog/2013/04/04/FAQ-Daily-Bread-in-the-UK.html

Closing this issue.
