### ISSUE TITLE
Dailybread fails with JS error

### ISSUE THREAD

**Issue by rufuspollock** [openspending/wheredoesmymoneygo.org#6]
You have a bug in: http://staging.wheredoesmymoneygo.org/dailybread.html

If I load the page and start clicking on the slider before the page has fully loaded (i.e. still spinning) I get:

<pre>
Uncaught TypeError: Cannot read property 'length' of undefined
OpenSpending.DailyBread.drawTierdailybread.js:132
OpenSpending.DailyBread.drawdailybread.js:115
OpenSpending.DailyBread.sliderUpdateddailybread.js:54
OpenSpending.DailyBread.init.$e.find.slider.slidedailybread.js:45
a.Widget._triggerjquery-ui.min.js:9
a.widget._slidejquery-ui.min.js:14
a.widget._mouseCapturejquery-ui.min.js:14
a.widget._mouseDownjquery-ui.min.js:9
a.widget._mouseInit.startedjquery-ui.min.js:9
c.event.handlejquery.min.js:63
c.event.add.h.handle.ojquery.min.js:5
</pre>

If I wait until loaded all is fine. You are probably not bind your event handlers in document ready :-)

**Comment by gka** [comment]
should be fixed now. the slider is now hidden until both the app and the data is loaded. instead, a loading message is shown.
